# - name: Download MySQL 5.7 repository configuration file
#   get_url:
#     url: https://repo.mysql.com/mysql57-community-release-el7-11.noarch.rpm
#     dest: /tmp/mysql57-community-release-el7-11.noarch.rpm

##Shadi Code works
- name: Import MySQL 5.7 GPG key
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: Install MySQL 5.7 repository
  yum_repository:
    name: mysql57-community
    description: MySQL 5.7 Community Server
    baseurl: https://repo.mysql.com//mysql57-community-release-el7-11.noarch.rpm
    gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    enabled: 1
    gpgcheck: 1

- name: install mysql repository 
  yum: 
    name: /tmp/mysql57-community-release-el7-11.noarch.rpm
    state: present

- name: install mysql 
  yum:
    name: mysql-community-server
    state: present
  notify: start mysql

# Sheraz Code works
# - name: Download the MySQL 5.7 Community Release RPM Linux
#   get_url:
#     url: https://repo.mysql.com//mysql57-community-release-el7-11.noarch.rpm
#     dest: /tmp/mysql57-community-release-el7-11.noarch.rpm

## import key is required first before installing any other mysql packages
# - name: Import MySQL GPG Key Linux
#   rpm_key:
#     state: present
#     key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

# - name: Install the MySQL 5.7 Community Release RPM Linux
#   yum:
#     name: /tmp/mysql57-community-release-el7-11.noarch.rpm
#     state: present

# - name: Install MySQL Linux
#   package:
#     name: mysql-community-server
#     state: present

